In [ ]:
#using linspace #
import numpy as np
c = np.linspace(5, 10, 5) #start, end, number of
c

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
#commonarays
d = np.ones((3,5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x = np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
y = np.eye(3) #creates a matrix with 1 as the diagnols and 0 as the non-diagnols
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
z = np.eye(3,2)
z

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
a = np.diag([1,2,3,4]) #construct a diagnol array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#creates an array using random
a = np.random.rand(4)
a

array([0.01413163, 0.36319792, 0.08436233, 0.9804249 ])

In [ ]:
a = np.array([1+2j, 5+1j])
a

array([1.+2.j, 5.+1.j])

In [ ]:
c = np.array([True,False,True])
display(c.dtype)

dtype('bool')

In [ ]:
a = np.arange(10)
print(a)
print(a[5])
print(a[-2])

[0 1 2 3 4 5 6 7 8 9]
5
8


In [ ]:
b = np.diag([1,2,3])
print(b)
print(b[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [ ]:
b[2,1]=10
b

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 10,  3]])

Slicing

In [ ]:
a=np.arange(10)
print(a[1:10])

[1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(10)
print(a[1:10:2])

[1 3 5 7 9]


In [ ]:
b = np.arange(10)
b[5:] = 10
print(b)

[ 0  1  2  3  4 10 10 10 10 10]


In [ ]:
a = np.arange(10)
b = a[::2]
np.shares_memory(a,b)

True

In [ ]:
c = a[::2].copy()
np.shares_memory(a,c)

False

In [ ]:
c[0] = 5
print(c)
print(a)

[5 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.random.randint(0,20,15)
print(a)

[18 18  6 17  8  0  0  0 10  2 18 13 16  5 11]


In [ ]:
mask = (a%2==0)

In [ ]:
even_numbers = a[mask]
even_numbers

array([18, 18,  6,  8,  0,  0,  0, 10,  2, 18, 16])

In [ ]:
a[mask]=-1
a

array([-1, -1, -1, 17, -1, -1, -1, -1, -1, -1, -1, 13, -1,  5, 11])

In [ ]:
a = np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
b = a[[2,3,5,3,4]]
print(b)

[20 30 50 30 40]


In [ ]:
a[[9,7]] = -200
print(a)
print(b)

[   0   10   20   30   40   50   60 -200   80 -200]
[20 30 50 30 40]


In [ ]:
print(a**2)

[    0   100   400   900  1600  2500  3600 40000  6400 40000]


In [ ]:
b = np.ones(10) + 1
print("b = ",b)
print("a - b = ",a-b)

b =  [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
a - b =  [  -2.    8.   18.   28.   38.   48.   58. -202.   78. -202.]


In [ ]:
c = np.diag([1,2,3,4])
print(c)
print("*"*100)
print(c*c)
print("*"*100)
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
****************************************************************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************************************************************************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
#element comparision
a=np.array([1,2,3,4])
b=np.array([6,2,9,4])
print(a==b)

[False  True False  True]


In [ ]:
print(a>b)

[False False False False]


In [ ]:
print(a<b)

[ True False  True False]


In [ ]:
print (np.array_equal(a,b))

False


In [ ]:
c=np.array([1,2,5,4])
print(np.array_equal(a,c))

False


Logical Operations

In [ ]:
a=np.array([1,0,0,1],dtype="bool")
b=np.array([0,1,0,1],dtype="bool")
print(np.logical_or(a,b))

[ True  True False  True]


In [ ]:
print(np.logical_not(a,b))

[False  True  True False]


Transcend

In [ ]:
a=np.arange(5)+1
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(np.log(a))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


Shape Mismatch

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,10])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Basic Reductions

In [ ]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [ ]:
y=np.array([[1,2],[3,4]])
print(y)
print("*"*100)
print(y.T)

[[1 2]
 [3 4]]
****************************************************************************************************
[[1 3]
 [2 4]]


In [ ]:
print(y.sum(axis=0)) #column wise sum

[4 6]


In [ ]:
print(y.sum(axis=1))

[3 7]


In [ ]:
print(y.max())

4


In [ ]:
print(y.argmin()) #index of minimun element

0


In [ ]:
print(y.argmax())  #index of maximun element

3


In [ ]:
print(np.all([True,False,False])) #logical and

False


In [ ]:
print(np.any([True,False,False])) #logical or

True


In [ ]:
a=np.zeros((50,50))
print(np.any(a!=0))

False


Statistics

In [ ]:
x = np.arange(1,10)
print(np.mean(x))

5.0


In [ ]:
y=np.array([[1,2,3],[3,4,5]])
print(np.mean(y,axis=0)) #column wise mean
print(np.mean(y,axis=1)) #row wise mean

[2. 3. 4.]
[2. 4.]


In [ ]:
print(np.std(x))

2.581988897471611


1. Write a numpy program to convert a list of numerical value into one dimensional NumPy array

In [ ]:
li=[1,2,3,4,5,6,7,8,9]
ar=np.array(li)
print(ar)

[1 2 3 4 5 6 7 8 9]


2. Write a NumPy program to create a 3x3 matrix with values ranging from 1 to 10

In [ ]:
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. WAP to sort along the first,last axis of an array

In [ ]:
a=np.array([[10,40,60],[20,30,50]])
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[10 40 60]
 [20 30 50]]
[[10 30 50]
 [20 40 60]]
[[10 40 60]
 [20 30 50]]


4.WAP to create continuous Flattened array

In [ ]:
a=np.array([[10,40],[30,20]])
print(np.sort(a,axis=None))

[10 20 30 40]


In [ ]:
5. WAP